kind: pipeline
type: docker
name: default

steps:
steps:
- name: first
  image: php
  commands:
  - echo “Output from first step”;

- name: second
  image: php
  commands:
  - echo “Output from second step”;

- name: third
  image: php
  commands:
  - echo “Output from third step”;

  depends_on:
  - first
  - second
